name: Build Go

on:
    workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: '1.24'

    # - name: Print Go version and environment
    #   id: vars
    #   run: |
    #     printf "Using go at: $(which go)\n"
    #     printf "Go version: $(go version)\n"
    #     printf "\n\nGo environment:\n\n"
    #     go env
    #     printf "\n\nSystem environment:\n\n"
    #     env
    #     echo "::set-output name=go_cache::$(go env GOCACHE)"

    # - name: Get dependencies
    #   run: go get -v -t -d ./...


    - name: Build
      working-directory: .
      # env:
      #   CGO_ENABLED: 0
      run: |
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/ApkCheckPack_windows_amd64.exe ./src
          tree .

      
    # - name: Build
    #   run: |
    #     sudo apt-get update -y
    #     sudo apt-get install make  -y
    #     sudo apt-get install iptables -y
    #     make
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: ApkCheckPack
        path: |
            bin/ApkCheckPack_windows_amd64.exe
